server:
  port: 8080

spring:
  application:
    name: gateway

eureka:
  instance:
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 3
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      default-zone: http://localhost:8761/eureka/
    registry-fetch-interval-seconds: 1

zuul:
  ribbon:
    eager-load: true
  ignored-headers: Cookie, Set-Cookie, Access-Control-Allow-Credentials, Access-Control-Allow-Origin
  ignored-services: '*'
  routes:
    api-server:
      path: /**

ribbon:
  server-list-refresh-interval: 1000

api-server:
  ribbon:
    Connect-timeout: 2500
    Read-timeout: 5000

logging:
  config: classpath:logback-spring.xml